[package]
name = "strata-storage-next"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["localfs"]
localfs = ["dep:fs2"]
testkit = []
fault-injection = ["testkit"]
perf-trace = []

[dependencies]
crc32fast = { workspace = true }
strata-core-next = { path = "../core-next" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fs2 = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
