use crate::support::*;

pub(super) fn arrow_outputs() -> Vec<Output> {
    vec![
        Output::ArrowImportResult(ArrowImportResult::new(
            ArrowImportTarget::Json,
            "empty.csv".to_owned(),
            0,
            0,
            0,
        )),
        Output::ArrowImportResult(ArrowImportResult::new(
            ArrowImportTarget::Kv,
            "input.parquet".to_owned(),
            10,
            1,
            2,
        )),
        Output::ArrowImportResult(ArrowImportResult::new(
            ArrowImportTarget::Vector,
            "vectors.jsonl".to_owned(),
            2,
            1,
            1,
        )),
        Output::ArrowExportResult(ArrowExportResult::new(
            ArrowExportPrimitive::Kv,
            ArrowFileFormat::Csv,
            vec!["kv.csv".to_owned()],
            0,
            0,
        )),
        Output::ArrowExportResult(ArrowExportResult::new(
            ArrowExportPrimitive::Json,
            ArrowFileFormat::Parquet,
            vec!["docs.parquet".to_owned()],
            2,
            1024,
        )),
        Output::ArrowExportResult(ArrowExportResult::new(
            ArrowExportPrimitive::Event,
            ArrowFileFormat::Jsonl,
            vec!["events.jsonl".to_owned()],
            2,
            512,
        )),
        Output::ArrowExportResult(ArrowExportResult::new(
            ArrowExportPrimitive::Vector,
            ArrowFileFormat::Jsonl,
            vec!["vectors.jsonl".to_owned()],
            2,
            512,
        )),
        Output::ArrowExportResult(ArrowExportResult::new(
            ArrowExportPrimitive::Graph,
            ArrowFileFormat::Parquet,
            vec![
                "graph_nodes.parquet".to_owned(),
                "graph_edges.parquet".to_owned(),
            ],
            11,
            1024,
        )),
    ]
}
