[package]
name = "strata-engine-next"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["localfs"]
localfs = ["strata-storage-next/localfs"]
testkit = []

[dependencies]
sha2 = { workspace = true }
strata-core-next = { path = "../core-next" }
strata-storage-next = { path = "../storage-next", default-features = false }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
